# Generated by Django 3.1.5 on 2021-02-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0003_remove_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zip',
        ),
    ]
