# Generated by Django 3.1.5 on 2021-02-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0004_auto_20210210_0822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
