# Generated by Django 3.1.5 on 2021-02-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0006_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
