# Generated by Django 3.1.5 on 2021-02-11 09:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0008_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='product',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), null=True, size=8),
        ),
    ]
