# Generated by Django 3.1.5 on 2021-02-11 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ECOM', '0009_shippingaddress_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='CartItem',
        ),
    ]
