# Generated by Django 3.1.5 on 2021-02-12 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ECOM', '0010_auto_20210211_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_address',
            field=models.TextField(default=''),
        ),
    ]
