# Generated by Django 3.1.5 on 2021-02-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0015_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='product',
        ),
    ]
