# Generated by Django 3.1.5 on 2021-02-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0019_ordereditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='Payment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
