# Generated by Django 3.1.5 on 2021-02-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0020_ordereditem_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
