# Generated by Django 3.1.5 on 2021-02-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOM', '0021_ordereditem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='orderID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='orderID',
            field=models.IntegerField(default=0),
        ),
    ]
