# Generated by Django 3.1.5 on 2021-02-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
